### ISSUE TITLE
Piping lava into the Magma Anvil doesn't update the GUI fill level

### ISSUE THREAD

**Issue by Mylimo** [PrinceOfAmber/Cyclic#939]
Minecraft version & Mod Version: 1.12.2 - 1.16.10
(Modpack: Stoneblock)

Single player or Server: Single player

Describe problem (what you were doing / what happened):
Filling the Magma Anvil with Fluid Pipes (tried both Cyclic and Extra Utilities ones) doesn't update the Lava fill level in the GUI. Does update the information you get when right-clicking though and works properly.

Crash log (if any): -

**Comment by PrinceOfAmber** [comment]
This looks fixed in 1.17.2 , i just tried with a simple setup of a tank and the anvil and the pipes

**Comment by netmc** [comment]
I'm in the latest stoneblock (1.0.26), and using the lava from a crucible with fluiducts just seems to void it.  I did let the pipe completely fill, then connected the anvil, and it actually filled partially with lava.  However subsequent input of lava did not change the amount of lava in the anvil.

**Comment by PrinceOfAmber** [comment]
Let me know if something else comes up https://minecraft.curseforge.com/projects/cyclic/files/2641400

**Comment by Dimentive** [comment]
I’m using Cyclic 1.18.0 (playing [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2), version 1.62), and I’m still having this issue.

**Comment by Dimentive** [comment]
I’m using Cyclic 1.18.0 (playing [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2), version 1.62), and I’m still having this issue. There are two newer versions of Cyclic, but the changelogs for them don’t mention this problem, so it probably happens in 1.18.2, too.

**Comment by Dimentive** [comment]
I’m using Cyclic 1.18.0 (playing [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2), version 1.62), and I’m still having this issue. I transferred lava from an Ender IO fluid tank to Cyclic’s magma anvil, and the GUI didn’t update. There are two newer versions of Cyclic, but the changelogs for them don’t mention this problem, so it probably happens in 1.18.2, too.

**Comment by Dimentive** [comment]
I’m using Cyclic 1.18.0 (playing [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2), version 1.62), and I’m still having this issue. I transferred lava from an Ender IO fluid tank to Cyclic’s magma anvil, and while it worked, the magma anvil’s lava bar didn’t update. There are two newer versions of Cyclic, but the changelogs for them don’t mention this problem, so it probably happens in 1.18.2, too.

**Comment by Dimentive** [comment]
I’m using Cyclic 1.18.0 (playing [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2), version 1.62), and I’m still having this issue. I transferred lava from an Ender IO fluid tank to Cyclic’s magma anvil (without cables, pipes, or conduits), and while it worked, the magma anvil’s lava bar didn’t update. There are two newer versions of Cyclic, but the changelogs for them don’t mention this problem, so it probably happens in 1.18.2, too.

**Comment by Dimentive** [comment]
I’m using Cyclic 1.18.0 (playing [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2), version 1.62), and I’m still having this issue. I transferred lava from an Ender IO fluid tank to Cyclic’s magma anvil (without conduits, cables, or pipes), and while it worked, the magma anvil’s lava bar didn’t update. There are two newer versions of Cyclic, but the changelogs for them don’t mention this problem, so it probably happens in 1.18.2, too.

**Comment by ClaudiusMinimus** [comment]
It seems this issue has returned in Cyclic 1.16.3-0.7.1. It say in JEI the anvil uses magma, and I've tried to put in Magma block manually or with hoppers and it does not work. 

I also have tried LAVA using Cyclic cables and it does not work either.
